# Generated by Django 2.0.5 on 2018-06-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file_url', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Container')),
            ],
        ),
    ]
