# Generated by Django 2.0.5 on 2018-06-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='container',
        ),
        migrations.RemoveField(
            model_name='object',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='object',
            name='name',
        ),
    ]
